title: "2bt's Blog"
#email: dnl.lngnr@gmail.com
#description: >-
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
url: "https://2bt.github.io"
domain: "2bt.github.io"
baseurl:
github_username: 2bt

theme: jekyll-theme-cayman
#theme: minima
